// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdiMZhflgmhSnzxpKpkioMoxyDPVN21Ig',
    appId: '1:647448464851:android:1a3e8a0199736a8dbff326',
    messagingSenderId: '647448464851',
    projectId: 'flutter-crud2-6ce95',
    storageBucket: 'flutter-crud2-6ce95.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqVnQ5qyKjw-0kqmHPJF02-v44qZTblMQ',
    appId: '1:647448464851:ios:ab77e50e5ec65526bff326',
    messagingSenderId: '647448464851',
    projectId: 'flutter-crud2-6ce95',
    storageBucket: 'flutter-crud2-6ce95.firebasestorage.app',
    iosBundleId: 'com.example.flutterCrud',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQgonfnS20ZH6I_pwd4G0to1zmbui3_Vs',
    appId: '1:647448464851:web:05da6025c16acc16bff326',
    messagingSenderId: '647448464851',
    projectId: 'flutter-crud2-6ce95',
    authDomain: 'flutter-crud2-6ce95.firebaseapp.com',
    storageBucket: 'flutter-crud2-6ce95.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqVnQ5qyKjw-0kqmHPJF02-v44qZTblMQ',
    appId: '1:647448464851:ios:ab77e50e5ec65526bff326',
    messagingSenderId: '647448464851',
    projectId: 'flutter-crud2-6ce95',
    storageBucket: 'flutter-crud2-6ce95.firebasestorage.app',
    iosBundleId: 'com.example.flutterCrud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQgonfnS20ZH6I_pwd4G0to1zmbui3_Vs',
    appId: '1:647448464851:web:ec59c9bd2b311d1dbff326',
    messagingSenderId: '647448464851',
    projectId: 'flutter-crud2-6ce95',
    authDomain: 'flutter-crud2-6ce95.firebaseapp.com',
    storageBucket: 'flutter-crud2-6ce95.firebasestorage.app',
  );

}